baseURL = "https://ferez96.com/blog"
title = "Ferez's blog"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false
copyright = '© 2026 Duong Thai Minh. All rights reserved.'

[languages]
  [languages.en]
    languageName = "English"
    languageCode = "en-us"
    weight = 1
    contentDir = "content/en"
    title = "Ferez's blog"
    [languages.en.params]
      description = "Personal blog powered by Hugo."

  [languages.vi]
    languageName = "Tiếng Việt"
    languageCode = "vi"
    weight = 2
    contentDir = "content/vi"
    title = "Blog của Ferez"
    [languages.vi.params]
      description = "Blog cá nhân."

[params]
  [params.author]
    email = 'minh9a4@gmail.com'
    name = 'Duong Thai Minh'
  [params.giscus]
    repo = "ferez96/blog"
    repo_id = "R_kgDOSTIULw"
    category = "Announcements"
    category_id = "DIC_kwDOSTIUL84C8QiB"
    mapping = "pathname"
    reactions_enabled = "1"
    emit_metadata = "0"
    input_position = "bottom"
    theme = "preferred_color_scheme"

[outputs]
  home = ['html', 'rss']
  section = ['html', 'rss']
  taxonomy = ['html']
  term = ['html']
